# === 通讯与轮询配置（模拟无需改） ===
mode: "rtu"
rtu:
  port: "/dev/ttyUSB0"
  baudrate: 9600
  parity: "N"
  stopbits: 1
  bytesize: 8
  timeout: 1.0
tcp:
  host: "192.168.1.100"
  port: 502

# 模拟轮询周期（毫秒）
poll_interval_ms: 1000
max_batch_len: 60

# 点表路径（若不存在，模拟器会自动生成一个示例点表）
tagmap_path: "generated_tagmap.json"

# 旧的单值 ID（保留无用）
cluster_id: 0
module_id: 0
sub_id: 0

# ★ 范围轮询：模拟将对这些范围内的 C/M/S 全部生成数据
ranges:
  clusters: "0-3"     # C0~C1
  modules:  [0,1,2]     # M0,M1
  subs:     "0-4"     # S0~S2

# 地址布局（与真实一致，虽然模拟不使用真实寄存器）
addr_layout:
  cluster:
    shift: 8
    base: 0
  module:
    shifts: {cluster: 9, module: 6}
    base: 0
  substack:
    shifts: {cluster: 10, module: 7, sub: 6}
    base: 0

# 前端键名与元信息
key_format: "{name}@C{c}M{m}S{s}"
include_meta: true
float_epsilon: 1e-6
