# 运行模式：rtu 或 tcp
mode: "rtu"

# RTU 串口配置
rtu:
  port: "/dev/ttyUSB0"
  baudrate: 9600
  parity: "N"
  stopbits: 1
  bytesize: 8
  timeout: 1.0

# TCP 配置（当 mode=tcp 时生效）
tcp:
  host: "192.168.1.10"
  port: 502
  timeout: 1.0

# 轮询与读取批次
poll_interval_ms: 10000
max_batch_len: 60
float_epsilon: 1e-6

# 默认 ID（当某层级为 -1 时使用）
cluster_id: 0
module_id:  0
sub_id:     0

# 层级范围展开（可写单值、列表、区间 "a-b"）
ranges:
  clusters: "0-1"   # 如 0 到 1 两个簇
  modules:  [0,1,2] # 三个模块
  subs:     0       # 没有子堆则可写 0

# 键名格式（默认 {name}@C{c}M{m}S{s}）
key_format: "{name}@C{c}M{m}S{s}"

# 地址布局（可选，按位移组合最终地址）
addr_layout:
  cluster:
    base: 0
    shift: 8
  module:
    base: 0
    shifts: { cluster: 9, module: 6 }
  substack:
    base: 0
    shifts: { cluster: 10, module: 7, sub: 6 }

# 是否在 WS/HTTP 返回 meta（c/m/s）
include_meta: true

# 点表路径（JSON）
tagmap_path: "generated_tagmap.json"

# 数据保留与清理
retention_days: 30            # 仅保留最近 30 天
cleanup_interval_hours: 6     # 每 6 小时执行一次后台清理

# SQLite 优化
sqlite:
  journal_mode: "WAL"
  synchronous: "NORMAL"
  auto_vacuum: "INCREMENTAL"
  page_size: 4096
  cache_size_mb: 64
